services:
  api:
    build: .
    working_dir: /app
    command: python -m uvicorn app:app --host 0.0.0.0 --port 8000 --app-dir src
    ports:
      - "8000:8000"
    volumes:
      - ./artifacts:/app/artifacts

  streamlit:
    build: .
    working_dir: /app
    command: python -m streamlit run /app/src/streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ./artifacts:/app/artifacts
